### ISSUE TITLE
spring-social-yahoo Maven repository

### ISSUE THREAD

**Issue by decisionwanted** [gabrielruiu/spring-social-yahoo#1]
Hello,

I'd like to include spring-social-yahoo into my project. Do you have a Maven reository for spring-social-yahoo ?

Thanks

**Comment by decisionwanted** [comment]
I think I found this one:

``` xml
        <dependency>
            <groupId>com.github.gabrielruiu</groupId>
            <artifactId>spring-social-yahoo</artifactId>
            <version>1.0.0.RELEASE</version>
        </dependency>
```

**Comment by gabrielruiu** [comment]
Yup, that's it :)

**Comment by gabrielruiu** [comment]
I'll add the maven dependency to the readme in the following version

**Comment by decisionwanted** [comment]
Thank you very much ! Could you please take a look into my other issue - https://github.com/gabrielruiu/spring-social-yahoo/issues/2. I'm completely blocked right now with it :(

**Comment by gabrielruiu** [comment]
Taking a look now to see what I can do
