### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by danjee** [gabrielruiu/spring-social-yahoo#5]
It's strange the lack of activity on Yahoo with Spring Social from the open source community. I wanted to ask if this project is still alive, if you accept PR and if you plan to make new releases on Maven central. I saw some functionalities are incomplete.
Thanks and nice work so far!

**Comment by gabrielruiu** [comment]
Hy!
Thanks for the interest in the project, and I apologize for the late response :(

The project has not been active for quite some time, unfortunately, but I am considering bringing it back to life now that you showed interest, so it might be useful to other people as well.

Keep an eye on the project for near-future updates.
